/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    works: Work;
    organizations: Organization;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor' | 'customer') | null;
  organization?: (number | null) | Organization;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title?: string | null;
  steps?:
    | {
        step: {
          title: string;
          is_completed: boolean;
        };
        id?: string | null;
      }[]
    | null;
  events?:
    | {
        event: {
          title: string;
          description: string;
          date: string;
          address: string;
          professional_name: string;
          profession?: string | null;
          contact_number?: string | null;
          contact_email?: string | null;
          instagram?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  projects?:
    | {
        project: {
          title: string;
          status: 'pending' | 'approved' | 'archived';
          type: 'executive' | 'wood_detailing' | 'wet_spaces_detailing';
          file: number | Media;
        };
        id?: string | null;
      }[]
    | null;
  renders?:
    | {
        files: number | Media;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        document: {
          title: string;
          type: 'offers' | 'briefings' | 'contracts' | 'meeting_minutes';
          file: number | Media;
        };
        id?: string | null;
      }[]
    | null;
  photos?:
    | {
        files: number | Media;
        id?: string | null;
      }[]
    | null;
  quotings?:
    | {
        quoting: {
          title: string;
          file: number | Media;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}